"""
CMIFE-YOLO Batch Training Script
Runs all ablation experiments sequentially.

Usage:
    python scripts/batch_train.py

Requirements:
    - Dataset must be converted to YOLO format first
    - Run convert_visdrone_to_yolo.py before this script
"""

import os
import sys
import time
import subprocess
from pathlib import Path
from datetime import datetime


# ============================================================================
# CONFIGURATION
# ============================================================================

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent.absolute()
DATASET_PATH = r'C:\Users\Administrator\Desktop\D035.VisDrone2019_YOLO'
MODEL_DIR = PROJECT_ROOT / 'ultralytics_cfg' / 'models' / '11'
OUTPUT_DIR = PROJECT_ROOT / 'runs' / 'cmife_exp'

# Training parameters
EPOCHS = 300
BATCH_SIZE = 8
IMG_SIZE = 640
DEVICE = 0  # 0 for GPU, 'cpu' for CPU
PRETRAINED = False
PATIENCE = 50

# Experiments configuration
# Format: (name, model_file, description)
EXPERIMENTS = [
    ('01_baseline', 'cmife-abl-a_baseline.yaml',
     'YOLO11n Baseline (No CMIFE)'),
    ('02_p3_single', 'cmife-abl-b_p3_single.yaml',
     'P3 Single CMIFE'),
    ('03_p3_dual', 'cmife-abl-c_p3_dual.yaml',
     'P3 Dual CMIFE'),
    ('04_p3_p4_dual', 'cmife-abl-d_p3_p4_dual.yaml',
     'P3 + P4 Dual CMIFE'),
    ('05_p3_p4_p5_dual', 'cmife-abl-e_p3_p4_p5_dual.yaml',
     'P3 + P4 + P5 Dual CMIFE'),
    ('06_full_cmife', 'cmife-abl-f_full.yaml',
     'Full CMIFE-YOLO (Dual CMIFE + Cross-Scale Fusion)'),
]


def get_model_path(model_file):
    """Get full path to model YAML file."""
    return MODEL_DIR / model_file


def run_training(exp_name, model_path, description):
    """Run a single training experiment."""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    run_name = f"{exp_name}_{timestamp}"

    project_path = OUTPUT_DIR / exp_name

    cmd = [
        'python', '-m', 'ultralytics', 'detect', 'train',
        '--model', str(model_path),
        '--data', 'VisDrone.yaml',
        '--epochs', str(EPOCHS),
        '--batch', str(BATCH_SIZE),
        '--imgsz', str(IMG_SIZE),
        '--device', str(DEVICE),
        '--pretrained', str(PRETRAINED).lower(),
        '--patience', str(PATIENCE),
        '--project', str(project_path),
        '--name', 'train',
        '--exist-ok',  # Overwrite if exists
        '--verbose',    # Show progress
        '--cache',      # Cache images for faster training
    ]

    print("\n" + "=" * 70)
    print(f"[EXPERIMENT] {description}")
    print(f"[MODEL] {model_path}")
    print(f"[OUTPUT] {project_path}")
    print(f"[CMD] {' '.join(cmd)}")
    print("=" * 70)

    start_time = time.time()

    try:
        result = subprocess.run(cmd, cwd=str(PROJECT_ROOT), check=True)
        elapsed = time.time() - start_time
        print(f"\n[SUCCESS] {exp_name} completed in {elapsed/3600:.1f} hours")
        return True, elapsed

    except subprocess.CalledProcessError as e:
        elapsed = time.time() - start_time
        print(f"\n[ERROR] {exp_name} failed after {elapsed/3600:.1f} hours")
        print(f"[ERROR CODE] {e.returncode}")
        return False, elapsed

    except KeyboardInterrupt:
        elapsed = time.time() - start_time
        print(f"\n[INTERRUPTED] {exp_name} interrupted after {elapsed/3600:.1f} hours")
        return False, elapsed


def check_dataset():
    """Check if dataset is ready."""
    dataset_path = Path(DATASET_PATH)

    required = [
        'VisDrone.yaml',
        'images/train',
        'images/val',
        'labels/train',
        'labels/val',
    ]

    all_exist = True
    for item in required:
        path = dataset_path / item if 'VisDrone.yaml' in item else dataset_path / item
        if not path.exists():
            print(f"[WARN] Missing: {path}")
            all_exist = False

    # Also check if VisDrone.yaml exists in the correct location
    yaml_path = PROJECT_ROOT / 'ultralytics_cfg' / 'datasets' / 'VisDrone.yaml'
    if not yaml_path.exists():
        print(f"[WARN] Missing: {yaml_path}")
        all_exist = False

    return all_exist


def create_dataset_yaml():
    """Create or update the VisDrone.yaml with correct paths."""
    yaml_content = f"""# CMIFE-YOLO VisDrone2019 Dataset Configuration
# Auto-generated by batch_train.py

path: {DATASET_PATH}
train: images/train
val: images/val
test: images/test

# Classes (VisDrone2019)
nc: 10
names:
  0: pedestrian
  1: people
  2: bicycle
  3: car
  4: van
  5: truck
  6: tricycle
  7: awning-tricycle
  8: bus
  9: motor
"""

    yaml_path = PROJECT_ROOT / 'ultralytics_cfg' / 'datasets' / 'VisDrone.yaml'
    yaml_path.parent.mkdir(parents=True, exist_ok=True)

    with open(yaml_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)

    print(f"[CONFIG] Created dataset YAML: {yaml_path}")
    return yaml_path


def print_summary(results):
    """Print training summary."""
    print("\n" + "=" * 70)
    print("TRAINING SUMMARY")
    print("=" * 70)

    total_time = 0
    for exp_name, model, desc, success, elapsed in results:
        status = "[OK]" if success else "[FAIL]"
        hours = elapsed / 3600
        print(f"  {status} {desc}: {hours:.1f} hours")
        total_time += elapsed

    print(f"\nTotal training time: {total_time/3600:.1f} hours")
    print(f"Results saved to: {OUTPUT_DIR}")
    print("=" * 70)


def main():
    """Main training loop."""
    print("=" * 70)
    print("CMIFE-YOLO Batch Training")
    print("=" * 70)
    print(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Project: {PROJECT_ROOT}")
    print(f"Dataset: {DATASET_PATH}")
    print(f"Epochs: {EPOCHS} | Batch: {BATCH_SIZE} | Device: {DEVICE}")
    print("=" * 70)

    # Step 1: Check/create dataset YAML
    print("\n[STEP 1] Preparing dataset configuration...")
    create_dataset_yaml()

    # Step 2: Verify dataset
    print("\n[STEP 2] Verifying dataset...")
    if not check_dataset():
        print("\n[ERROR] Dataset not ready!")
        print("[ERROR] Please run convert_visdrone_to_yolo.py first!")
        print("[ERROR] Then run this script again.")
        sys.exit(1)

    print("[OK] Dataset verified!")

    # Step 3: Run experiments
    print(f"\n[STEP 3] Starting {len(EXPERIMENTS)} experiments...")
    results = []

    for i, (exp_name, model_file, description) in enumerate(EXPERIMENTS):
        print(f"\n[PROGRESS] Experiment {i+1}/{len(EXPERIMENTS)}")

        model_path = get_model_path(model_file)
        if not model_path.exists():
            print(f"[ERROR] Model file not found: {model_path}")
            results.append((exp_name, model_file, description, False, 0))
            continue

        success, elapsed = run_training(exp_name, model_path, description)
        results.append((exp_name, model_file, description, success, elapsed))

        # Small delay between experiments
        if i < len(EXPERIMENTS) - 1:
            print("\n[WAIT] Waiting 5 seconds before next experiment...")
            time.sleep(5)

    # Print summary
    print_summary(results)

    print(f"\nEnd time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("[DONE] All experiments completed!")


if __name__ == '__main__':
    main()
